server:
  port: 8099
spring:
  application:
    name: duolaimall-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    inetutils:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 192.168.1.8
    gateway:
      routes:
        - id: duolai-order
          uri: lb://duolai-order
          predicates:
            - Path=/shopping/order/**,/shopping/cancelOrder
        - id: duolai-user
          uri: lb://duolai-user
          predicates:
            - Path=/user/**, /shopping/addresses
        - id: duolai-promo
          uri: lb://duolai-promo
          predicates:
            - Path=/shopping/seckilllist/**,/shopping/promoProductDetail,/shopping/seckill
        - id: duolai-search
          uri: lb://duolai-search
          predicates:
            - Path=/shopping/search/**,/shopping/searchHotWord
        - id: duolai-shopping
          uri: lb://duolai-shopping
          predicates:
            - Path=/shopping/**
        - id: duolai-pay
          uri: lb://duolai-pay
          predicates:
            - Path=/cashier/**,/image/**
logging:
  level:
    org.springframework.cloud.gateway: debug

cskaoyan:
  mall:
    skipUrls:
      - /shopping/homepage
      - /shopping/navigation
      - /shopping/categories
      - /shopping/goods
      - /shopping/product/**
      - /shopping/recommend
      - /user/register
      - /user/verify
      - /user/login
      - /user/kaptcha
      - /image/**
      - /shopping/search/**
      - /shopping/searchHotWord
      - /shopping/promoProductDetail
      - /shopping/seckilllist
      - /shopping/test/**
