server:
  port: 8101
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com.cskaoyan.user.dal/persistence/*Mapper.xml"
  type-aliases-package: com.cskaoyan.user.dal.entitys

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

